# Generated by Django 4.1.7 on 2024-05-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacherdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Teachers Information',
            },
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('ParentName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=70)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
            ],
            options={
                'verbose_name_plural': 'Students Information',
            },
        ),
    ]
