# Generated by Django 4.1.7 on 2024-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='Age',
            field=models.IntegerField(default=1),
        ),
    ]
